[package]
name = "door-server"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
log = "0.4"
rppal = { version = "0.12", features = ["hal"] }
serde_json = "1"
webthing = { version = "0.14.0", git = "https://github.com/reitermarkus/webthing-rust", branch = "if-let-match" }
actix-rt = "1.1"
uuid = "0.8.2"
embedded-hal = "1.0.0-alpha.4"
embedded-hal-0 = { version = "0.2.6", package = "embedded-hal" }
ws2812-spi = "0.4.0"
smart-leds = "0.3.0"

[lib]
name = "door_server"
path = "src/lib.rs"

[[bin]]
name = "door-server"
path = "src/main.rs"

[patch.crates-io]
rppal = { git = "https://github.com/golemparts/rppal" }
