[package]
name = "door-server"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
log = "0.4"
rppal = "0.12"
serde_json = "1"
webthing = "0.14.0"
actix-rt = "1.1"
uuid = "0.8.2"

[lib]
name = "door_server"
path = "src/lib.rs"

[[bin]]
name = "door-server"
path = "src/main.rs"
